export enum ConfigEnum {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_AUTH_SOURCE = 'DATABASE_AUTH_SOURCE',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRES = 'JWT_EXPIRES',
  OPS_KEY = 'OPS_KEY',
  ORIGIN = 'ORIGIN',
  BCRYPT_SECRET_ROUND = 'BCRYPT_SECRET_ROUND',
  PORT = 'PORT',
}
