export enum ConfigEnvEnum {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_AUTH_SOURCE = 'DATABASE_AUTH_SOURCE',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRES = 'JWT_EXPIRES',
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_EXPIRES = 'SESSION_EXPIRES',
  OPS_KEY = 'OPS_KEY',
  ORIGIN = 'ORIGIN',
  BCRYPT_SECRET_ROUND = 'BCRYPT_SECRET_ROUND',
  PORT = 'PORT',
  HOSTNAME = 'HOSTNAME',
  MAIN_HOSTNAME = 'MAIN_HOSTNAME',
  STORAGE_ENDPOINT = 'STORAGE_ENDPOINT',
  MINIO_ACCESS_KEY = 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY = 'MINIO_SECRET_KEY',
  MINIO_SERVER_ENDPOINT = 'MINIO_SERVER_ENDPOINT',
  MINIO_SERVER_PORT = 'MINIO_SERVER_PORT',
  MINIO_SERVER_SSL = 'MINIO_SERVER_SSL',
}

export type ConfigEnvType = {
  [key in ConfigEnvEnum]: string;
};
